# we must pass 2 variables
#1. component
#2. envirnoment
- name: "configure {{ component }} server"
  hosts: all
  become: yes
  vars_files:
  - "variables-{{ envirnoment }}.yaml"
  roles: 
  - "{{ component }}"